### ISSUE TITLE
RELACIONES(PRACTICA3)

### ISSUE THREAD

**Issue by carla1131** [SistemasTecTlaxiaco/actividad-6-practica-de-relaciones-2363#1]
[BAUTISTA_LEON_CARLA_1AS_RELACIONES.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-relaciones-2363/files/12826192/BAUTISTA_LEON_CARLA_1AS_RELACIONES.pdf)

**Comment by LuisAlexisMorales** [comment]
Portada: 25%
Procedimiento: 22%
Figuras, ilustraciones y figuras: 25%
Resultados y conclusiones: 20%
Total: 16.4/20
Evaluó equipo de Luis Alexis Morales Jose.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
