### ISSUE TITLE
Relaciones 

### ISSUE THREAD

**Issue by Mari-00** [SistemasTecTlaxiaco/actividad-6-practica-de-relaciones-2363#4]
[practica_2.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-relaciones-2363/files/12826352/practica_2.pdf)

**Comment by LuisAlexisMorales** [comment]
Portada: 25%
Procedimiento: 22%
Figuras, ilustraciones y figuras: 25%
Resultados y conclusiones: 22%
Total: 18.8/20
Evaluó equipo de Luis Alexis Morales Jose

**Comment by josealfredo79** [comment]
Bien hecho...y revisado...
