### ISSUE TITLE
Matemáticas-discretas

### ISSUE THREAD

**Issue by Anais-droid** [SistemasTecTlaxiaco/actividad-6-practica-de-relaciones-2363#6]
[Práctica-matemáticas discretas-3114.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-relaciones-2363/files/12826396/Practica-matematicas.discretas-3114.pdf)

**Comment by josealfredo79** [comment]
Calificacion

**Comment by LuisAlexisMorales** [comment]
Portada: 25%
Procedimiento: 25%
Figuras, ilustraciones y figuras: 25%
Resultados y conclusiones: 15%
Total: 18/20
Evaluó equipo de Luis Alexis Morales Jose .
